name: social_media_feed
description: "A Simple Social Media App Developed by Harsh H. Rajpurohit (Google Me)"
publish_to: 'none'
# App Version
version: 1.0.1+1

environment:
  sdk: ^3.5.2


# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # For using cupertino icons
  cupertino_icons: ^1.0.8

  # For integrating firebase
  firebase_core: ^3.6.0

  # For handling firebase authentication
  firebase_auth: ^5.3.1

  # For accessing cloud firestore database
  cloud_firestore: ^5.4.4
  
  # Bloc (State Management)
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  
  # Login UI
  flutter_login: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Good Practices
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
